server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/public
    username: postgres
    password: pass
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect